ROAST=[
    "You're not the sharpest tool in the shed, you're the instruction manual.",
    "You bring everyone so much joy when you leave the room.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "If laziness were an Olympic sport, you'd come in fourth so you wouldn't have to walk to the podium.",
    "You're proof that even evolution takes coffee breaks.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "You have something on your chin... no, the third one down.",
    "You're not stupid; you just have bad luck thinking.",
    "You have the kind of face that makes onions cry.",
    "I'd agree with you, but then we'd both be wrong.",
    "You're like a software update nobody asked for.",
    "Your personality has a free trial vibe.",
    "You’re the human version of a typo.",
    "You have the confidence of someone who has never checked their facts.",
    "You're not extra, you're unnecessary DLC.",
    "You radiate strong 'reply all' energy.",
    "You could trip over a cordless phone.",
    "You're the reason shampoo has instructions.",
    "Your jokes have a very strong loading-screen energy.",
    "You’re like a group project member who says 'we' a lot.",
    "You bring chaos to places that were already organized.",
    "You're a few fries short of a happy meal, and somehow proud of it.",
    "You're the reason the gene pool needs a lifeguard.",
    "You have two brain cells and both are fighting for third place.",
    "You're about as useful as a screen door on a submarine.",
    "You have the dramatic range of a low-battery notification.",
    "You're the offline version of a broken link.",
    "Your vibe is expired coupon.",
    "You manage to miss the point with impressive consistency.",
    "You’re not hard to ignore, but people still practice.",
    "You're like a password hint: confusing and not helpful.",
    "You’re built like a side quest nobody finishes.",
    "You make common sense look rare.",
    "You have the energy of a microwave at 2 a.m.",
    "You're not a mess, you're a limited-edition disaster.",
    "You talk like your thoughts are buffering.",
    "You're a bold mix of confidence and incorrectness.",
    "You have resting inconvenience face.",
    "You're the human equivalent of stepping on a LEGO.",
    "Your opinions are sponsored by zero research.",
    "You look like you clap when the plane lands.",
    "You couldn’t pour water out of a boot with instructions on the heel.",
    "You're the reason meetings could have been emails.",
    "You have all the depth of a puddle in July.",
    "You sound like an NPC with only one dialogue option.",
    "You’re what happens when autocorrect gives up.",
    "You couldn't find your way out of a revolving door.",
    "Your confidence is doing all the heavy lifting.",
    "You have the charisma of a wet sock.",
    "You're not iconic, you're ironic.",
    "You’re like a chair with one short leg: off-balance and annoying.",
    "You bring the same energy as a skipped ad that won’t skip.",
    "You're the plot twist nobody needed.",
    "Your ideas arrive pre-rejected.",
    "You’re the human equivalent of accidental caps lock.",
    "You make awkward look ambitious.",
    "You're like a phone at 1 percent: stressful and unreliable.",
    "You couldn't lead a fish to water.",
    "Your brain takes the scenic route on every thought.",
    "You're not intimidating, just loudly confusing.",
    "You have a talent for being technically present.",
    "You're like glitter: everywhere and hard to get rid of.",
    "You have the timing of a pop-up ad.",
    "You’re what a loading bar feels like emotionally.",
    "You act like a plot armor character in a reality show.",
    "You’re a strong argument for mute buttons.",
    "You have the grace of a shopping cart with one stuck wheel.",
    "Your thought process needs a customer support line.",
    "You have all the appeal of a terms-and-conditions page.",
    "You’re like a pencil with no lead: pointless.",
    "You make confusion look like a strategy.",
    "You have the problem-solving skills of a goldfish in a maze.",
    "You’re a sequel nobody greenlit.",
    "Your attention span has a witness protection program.",
    "You're the human version of low-resolution.",
    "You have a real gift for saying nothing with confidence.",
    "You make bad ideas sound underprepared.",
    "You're like a bookmark in a movie theater: wrong place, wrong format.",
    "You carry yourself like a rumor.",
    "You could ruin a free sample.",
    "You’re not the main character, you’re the loading tip.",
    "Your brain runs on trial software.",
    "You have all the structure of a spaghetti bridge.",
    "You're a reminder that not every thought needs to be shared.",
    "You’re like decaf drama: unnecessary and disappointing.",
    "You have the consistency of weak Wi-Fi.",
    "You make simple tasks feel handcrafted.",
    "You’re not mysterious, people just stop listening halfway through.",
    "Your best quality is that conversations with you eventually end.",
    "You have the ambition of a nap and the follow-through of a sneeze.",
    "You're like a mystery box filled with packing peanuts.",
    "You make mediocrity look competitive.",
    "You couldn’t organize a two-car parade.",
    "You have the aura of someone who says 'trust me' right before disaster.",
    "You're the kind of person who loses arguments to automatic doors.",
    "Your logic tree has no branches.",
    "You’re a walking reminder that volume is not substance.",
    "You have the problem-solving energy of unplugging something and hoping.",
    "You're not ahead of your time; your time just left.",
    "You make overthinking look undercooked.",
    "You’re like a calendar with no dates: decorative, but not useful.",
    "Your self-awareness is on airplane mode.",
    "You’re the human embodiment of 'well, that didn’t help.'"
]